---
# tasks file for k8s_Master_Config
- name: "Installation of Docker"
  package:
          name: docker
          state: present
 
- name: "Enabling Docker Service"
  service:
          name: docker 
          state: started
          enabled: yes

- name: "Repoistory for K8s"
  copy:
       src: /root/K8s_Cluster/k8s_Master_Config/files/k8s.repo
       dest: /etc/yum.repos.d/k8s.repo

- name: "Installation kubeadm, kubeclt, kubelet"
  yum:
      name: "{{ item }}"
      state: present
      disable_excludes: kubernetes
  loop:
       - kubelet
       - kubeadm
       - kubectl

- name: "Enabling kubelet Service"
  service:
          name: kubelet
          state: started
          enabled: yes

- name: "Pulling requider Images using kubeadm"
  shell: kubeadm config images pull
  changed_when: false

- name: "Changing driver in the docker"
  copy:
       src: /root/K8s_Cluster/k8s_Master_Config/files/daemon.json 
       dest: /etc/docker/daemon.json
  register: output

- name: "Restarting Docker Service"
  service:
          name: docker 
          state: restarted 
  when: output.changed == true

- name: "Installation iproute-tc"
  package:
          name: iproute-tc
          state: present

- name: "Setting bridge-nf-call-iptables to 1"
  copy :
        src: /root/K8s_Cluster/k8s_Master_Config/files/k8s.conf
        dest: /etc/sysctl.d/k8s.conf
  changed_when: false

- name: Restart Service
  shell: sudo sysctl --system

- name: "Disable SELinux"
  shell: "{{ item }}"
  loop:
       - sudo setenforce 0
       - sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
  ignore_errors: yes

- name: Initialization of Master
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem --node-name=master
  ignore_errors: yes

- name: Disable SWAP
  shell: "{{ item }}"
  loop:
       - "sudo sed -i '/swap/d' /etc/fstab"
       - "sudo swapoff -a"

- name: Creating .kube directory
  shell: "mkdir -p $HOME/.kube"

- name: Copying /etc/kubernetes/admin.conf $HOME/.kube/config
  shell: "sudo cp -i /etc/kubernetes/admin.conf  $HOME/.kube/config"

- name: Changing Owner Permission
  shell: "sudo chown $(id -u):$(id -g) $HOME/.kube/config"

- name: Configuring with flannel plugin
  shell: "kubectl apply  -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

- name: "Generating Token"
  shell: "kubeadm token create  --print-join-command"
  register: token
  ignore_errors: yes

- debug:
        var: token.stdout_lines
